# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created: Tue Mar 17 10:47:11 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(623, 389)
        Editor.setMinimumSize(QtCore.QSize(0, 0))
        Editor.setWindowTitle("Editor")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/table_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/images/images/table_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Editor.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setAutoScroll(False)
        self.tableView.setAutoScrollMargin(1)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 6, 0, 1, 1)
        self.queryTextEdit = QtGui.QLineEdit(self.centralwidget)
        self.queryTextEdit.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.queryTextEdit.setObjectName("queryTextEdit")
        self.gridLayout.addWidget(self.queryTextEdit, 1, 0, 1, 1)
        self.stqrtQueryButton = QtGui.QPushButton(self.centralwidget)
        self.stqrtQueryButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stqrtQueryButton.setObjectName("stqrtQueryButton")
        self.gridLayout.addWidget(self.stqrtQueryButton, 3, 0, 1, 1)
        Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Daten = QtGui.QMenu(self.menubar)
        self.menu_Daten.setObjectName("menu_Daten")
        self.menu_Exportieren = QtGui.QMenu(self.menu_Daten)
        self.menu_Exportieren.setObjectName("menu_Exportieren")
        self.menu_SQL = QtGui.QMenu(self.menubar)
        self.menu_SQL.setObjectName("menu_SQL")
        self.menuAnsicht = QtGui.QMenu(self.menubar)
        self.menuAnsicht.setObjectName("menuAnsicht")
        Editor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor)
        self.statusbar.setObjectName("statusbar")
        Editor.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Editor)
        self.toolBar.setObjectName("toolBar")
        Editor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_xls = QtGui.QAction(Editor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/file_extension_xls.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_xls.setIcon(icon1)
        self.action_xls.setObjectName("action_xls")
        self.action_anwenden = QtGui.QAction(Editor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_anwenden.setIcon(icon2)
        self.action_anwenden.setObjectName("action_anwenden")
        self.action_loeschen = QtGui.QAction(Editor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_loeschen.setIcon(icon3)
        self.action_loeschen.setObjectName("action_loeschen")
        self.action_zurueck = QtGui.QAction(Editor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/arrow_undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_zurueck.setIcon(icon4)
        self.action_zurueck.setObjectName("action_zurueck")
        self.action_newline = QtGui.QAction(Editor)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_newline.setIcon(icon5)
        self.action_newline.setObjectName("action_newline")
        self.actionAntworten_exportieren = QtGui.QAction(Editor)
        self.actionAntworten_exportieren.setEnabled(False)
        self.actionAntworten_exportieren.setStatusTip("")
        self.actionAntworten_exportieren.setObjectName("actionAntworten_exportieren")
        self.action_Importieren = QtGui.QAction(Editor)
        self.action_Importieren.setObjectName("action_Importieren")
        self.actionSqlQuery = QtGui.QAction(Editor)
        self.actionSqlQuery.setCheckable(True)
        self.actionSqlQuery.setObjectName("actionSqlQuery")
        self.menu_Exportieren.addAction(self.action_xls)
        self.menu_Daten.addAction(self.menu_Exportieren.menuAction())
        self.menu_Daten.addAction(self.action_Importieren)
        self.menu_SQL.addAction(self.actionAntworten_exportieren)
        self.menuAnsicht.addAction(self.actionSqlQuery)
        self.menubar.addAction(self.menu_Daten.menuAction())
        self.menubar.addAction(self.menuAnsicht.menuAction())
        self.menubar.addAction(self.menu_SQL.menuAction())
        self.toolBar.addAction(self.action_anwenden)
        self.toolBar.addAction(self.action_zurueck)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_newline)
        self.toolBar.addAction(self.action_loeschen)
        self.toolBar.addSeparator()

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        self.stqrtQueryButton.setText(QtGui.QApplication.translate("Editor", "SQL QUERY", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Daten.setTitle(QtGui.QApplication.translate("Editor", "&Daten", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Exportieren.setTitle(QtGui.QApplication.translate("Editor", "&Exportieren", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_SQL.setTitle(QtGui.QApplication.translate("Editor", "SQL-Abfrage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAnsicht.setTitle(QtGui.QApplication.translate("Editor", "Ansicht", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Editor", "Werkzeugleiste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_xls.setText(QtGui.QApplication.translate("Editor", "als .xls", None, QtGui.QApplication.UnicodeUTF8))
        self.action_anwenden.setText(QtGui.QApplication.translate("Editor", "Änderungen anwenden", None, QtGui.QApplication.UnicodeUTF8))
        self.action_anwenden.setToolTip(QtGui.QApplication.translate("Editor", "Änderungen übernehmen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_anwenden.setStatusTip(QtGui.QApplication.translate("Editor", "Änderungen übernehmen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loeschen.setText(QtGui.QApplication.translate("Editor", "Eintrag löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loeschen.setToolTip(QtGui.QApplication.translate("Editor", "Markierten Eintrag löschen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loeschen.setStatusTip(QtGui.QApplication.translate("Editor", "Markierten Eintrag löschen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_zurueck.setText(QtGui.QApplication.translate("Editor", "Rückgängig", None, QtGui.QApplication.UnicodeUTF8))
        self.action_zurueck.setToolTip(QtGui.QApplication.translate("Editor", "Änderungen rückgängig machen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_zurueck.setStatusTip(QtGui.QApplication.translate("Editor", "Änderungen rückgängig machen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_newline.setText(QtGui.QApplication.translate("Editor", "Neue Zeile", None, QtGui.QApplication.UnicodeUTF8))
        self.action_newline.setToolTip(QtGui.QApplication.translate("Editor", "Fügt eine neue Zeile in die Datenbank ein.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_newline.setStatusTip(QtGui.QApplication.translate("Editor", "Neue Zeile am Ende der Datenbank hinzufügen.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAntworten_exportieren.setText(QtGui.QApplication.translate("Editor", "Antworten exportieren", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Importieren.setText(QtGui.QApplication.translate("Editor", "Datenbank &importieren", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Importieren.setToolTip(QtGui.QApplication.translate("Editor", "Importiert eine Datenbank", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Importieren.setShortcut(QtGui.QApplication.translate("Editor", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSqlQuery.setText(QtGui.QApplication.translate("Editor", "SQL Query", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
