# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_v3.ui'
#
# Created: Tue Mar 17 10:39:31 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 731)
        MainWindow.setMinimumSize(QtCore.QSize(345, 731))
        MainWindow.setBaseSize(QtCore.QSize(299, 632))
        MainWindow.setStyleSheet("/*QMainWindow{\n"
"    background-color: rgb(85, 255, 0);\n"
"    background-color:rgb(165, 165, 165);\n"
"    /*color:white;*/\n"
"\n"
"\n"
"QGroupBox {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                       stop: 0 rgb(200, 200, 200), stop: 1 #FFFFFF);\n"
"    /*background-color:rgb(200, 200, 200);*/\n"
"     border: 1px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 1ex; /* leave space at the top for the title */\n"
"    font: bold;\n"
" }\n"
"\n"
" QGroupBox::title {\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top center; /* position at the top center */\n"
"     padding: 0 7px;\n"
"     background-color: /*rgb(200, 200, 200);*/\n"
"                                    qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 rgb(200, 200, 200), stop: 1 #FFFFFF);\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
" }\n"
"\n"
" QGroupBox::indicator {\n"
"     width: 13px;\n"
"     height: 13px;\n"
" }\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"/*\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"*/\n"
"QPushButton:on\n"
"{\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    background-color: rgb(0, 255, 0);\n"
"    border-radius: 1px\n"
"}\n"
"/*\n"
"QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"*/")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(91, 61))
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinbox = QtGui.QSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinbox.setFont(font)
        self.spinbox.setMinimum(1)
        self.spinbox.setMaximum(99999)
        self.spinbox.setProperty("value", 1)
        self.spinbox.setObjectName("spinbox")
        self.verticalLayout.addWidget(self.spinbox)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(90, 0))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editProtokollant = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editProtokollant.sizePolicy().hasHeightForWidth())
        self.editProtokollant.setSizePolicy(sizePolicy)
        self.editProtokollant.setMinimumSize(QtCore.QSize(10, 0))
        self.editProtokollant.setMaximumSize(QtCore.QSize(16777215, 31))
        self.editProtokollant.setBaseSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(14)
        self.editProtokollant.setFont(font)
        self.editProtokollant.setMaxLength(100)
        self.editProtokollant.setObjectName("editProtokollant")
        self.verticalLayout_2.addWidget(self.editProtokollant)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.groupBoxArtLaenge = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxArtLaenge.sizePolicy().hasHeightForWidth())
        self.groupBoxArtLaenge.setSizePolicy(sizePolicy)
        self.groupBoxArtLaenge.setMinimumSize(QtCore.QSize(221, 191))
        self.groupBoxArtLaenge.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBoxArtLaenge.setAutoFillBackground(False)
        self.groupBoxArtLaenge.setCheckable(True)
        self.groupBoxArtLaenge.setChecked(True)
        self.groupBoxArtLaenge.setObjectName("groupBoxArtLaenge")
        self.gridLayout = QtGui.QGridLayout(self.groupBoxArtLaenge)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBab10 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBab10.sizePolicy().hasHeightForWidth())
        self.buttonBab10.setSizePolicy(sizePolicy)
        self.buttonBab10.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBab10.setCheckable(True)
        self.buttonBab10.setAutoExclusive(True)
        self.buttonBab10.setObjectName("buttonBab10")
        self.gridLayout.addWidget(self.buttonBab10, 3, 5, 1, 1)
        self.buttonRot20 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRot20.sizePolicy().hasHeightForWidth())
        self.buttonRot20.setSizePolicy(sizePolicy)
        self.buttonRot20.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonRot20.setCheckable(True)
        self.buttonRot20.setAutoExclusive(True)
        self.buttonRot20.setObjectName("buttonRot20")
        self.gridLayout.addWidget(self.buttonRot20, 5, 1, 1, 1)
        self.buttonRot10 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRot10.sizePolicy().hasHeightForWidth())
        self.buttonRot10.setSizePolicy(sizePolicy)
        self.buttonRot10.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonRot10.setCheckable(True)
        self.buttonRot10.setAutoExclusive(True)
        self.buttonRot10.setObjectName("buttonRot10")
        self.gridLayout.addWidget(self.buttonRot10, 5, 2, 1, 1)
        self.buttonLac60 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLac60.sizePolicy().hasHeightForWidth())
        self.buttonLac60.setSizePolicy(sizePolicy)
        self.buttonLac60.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonLac60.setCheckable(True)
        self.buttonLac60.setAutoExclusive(True)
        self.buttonLac60.setObjectName("buttonLac60")
        self.gridLayout.addWidget(self.buttonLac60, 10, 2, 1, 1)
        self.buttonLac50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLac50.sizePolicy().hasHeightForWidth())
        self.buttonLac50.setSizePolicy(sizePolicy)
        self.buttonLac50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonLac50.setCheckable(True)
        self.buttonLac50.setAutoExclusive(True)
        self.buttonLac50.setObjectName("buttonLac50")
        self.gridLayout.addWidget(self.buttonLac50, 10, 3, 1, 1)
        self.buttonRot30 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRot30.sizePolicy().hasHeightForWidth())
        self.buttonRot30.setSizePolicy(sizePolicy)
        self.buttonRot30.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonRot30.setCheckable(True)
        self.buttonRot30.setAutoExclusive(True)
        self.buttonRot30.setObjectName("buttonRot30")
        self.gridLayout.addWidget(self.buttonRot30, 5, 0, 1, 1)
        self.buttonAal30 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAal30.sizePolicy().hasHeightForWidth())
        self.buttonAal30.setSizePolicy(sizePolicy)
        self.buttonAal30.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonAal30.setCheckable(True)
        self.buttonAal30.setAutoExclusive(True)
        self.buttonAal30.setObjectName("buttonAal30")
        self.gridLayout.addWidget(self.buttonAal30, 2, 2, 1, 1)
        self.buttonMai40 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMai40.sizePolicy().hasHeightForWidth())
        self.buttonMai40.setSizePolicy(sizePolicy)
        self.buttonMai40.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMai40.setCheckable(True)
        self.buttonMai40.setAutoExclusive(True)
        self.buttonMai40.setObjectName("buttonMai40")
        self.gridLayout.addWidget(self.buttonMai40, 8, 1, 1, 1)
        self.buttonLac80 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLac80.sizePolicy().hasHeightForWidth())
        self.buttonLac80.setSizePolicy(sizePolicy)
        self.buttonLac80.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonLac80.setCheckable(True)
        self.buttonLac80.setAutoExclusive(True)
        self.buttonLac80.setObjectName("buttonLac80")
        self.gridLayout.addWidget(self.buttonLac80, 10, 0, 1, 1)
        self.buttonRot0 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRot0.sizePolicy().hasHeightForWidth())
        self.buttonRot0.setSizePolicy(sizePolicy)
        self.buttonRot0.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonRot0.setCheckable(True)
        self.buttonRot0.setAutoExclusive(True)
        self.buttonRot0.setObjectName("buttonRot0")
        self.gridLayout.addWidget(self.buttonRot0, 5, 3, 1, 1)
        self.buttonNas40 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNas40.sizePolicy().hasHeightForWidth())
        self.buttonNas40.setSizePolicy(sizePolicy)
        self.buttonNas40.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonNas40.setCheckable(True)
        self.buttonNas40.setAutoExclusive(True)
        self.buttonNas40.setObjectName("buttonNas40")
        self.gridLayout.addWidget(self.buttonNas40, 1, 1, 1, 1)
        self.buttonAal40 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAal40.sizePolicy().hasHeightForWidth())
        self.buttonAal40.setSizePolicy(sizePolicy)
        self.buttonAal40.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonAal40.setCheckable(True)
        self.buttonAal40.setAutoExclusive(True)
        self.buttonAal40.setObjectName("buttonAal40")
        self.gridLayout.addWidget(self.buttonAal40, 2, 1, 1, 1)
        self.buttonBab50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBab50.sizePolicy().hasHeightForWidth())
        self.buttonBab50.setSizePolicy(sizePolicy)
        self.buttonBab50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBab50.setCheckable(True)
        self.buttonBab50.setAutoExclusive(True)
        self.buttonBab50.setObjectName("buttonBab50")
        self.gridLayout.addWidget(self.buttonBab50, 3, 1, 1, 1)
        self.buttonBra50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBra50.sizePolicy().hasHeightForWidth())
        self.buttonBra50.setSizePolicy(sizePolicy)
        self.buttonBra50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBra50.setCheckable(True)
        self.buttonBra50.setAutoExclusive(True)
        self.buttonBra50.setObjectName("buttonBra50")
        self.gridLayout.addWidget(self.buttonBra50, 4, 1, 1, 1)
        self.buttonBra30 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBra30.sizePolicy().hasHeightForWidth())
        self.buttonBra30.setSizePolicy(sizePolicy)
        self.buttonBra30.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBra30.setCheckable(True)
        self.buttonBra30.setAutoExclusive(True)
        self.buttonBra30.setObjectName("buttonBra30")
        self.gridLayout.addWidget(self.buttonBra30, 4, 3, 1, 1)
        self.buttonMen90 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMen90.sizePolicy().hasHeightForWidth())
        self.buttonMen90.setSizePolicy(sizePolicy)
        self.buttonMen90.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMen90.setCheckable(True)
        self.buttonMen90.setAutoExclusive(True)
        self.buttonMen90.setObjectName("buttonMen90")
        self.gridLayout.addWidget(self.buttonMen90, 9, 0, 1, 1)
        self.buttonMai50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMai50.sizePolicy().hasHeightForWidth())
        self.buttonMai50.setSizePolicy(sizePolicy)
        self.buttonMai50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMai50.setCheckable(True)
        self.buttonMai50.setAutoExclusive(True)
        self.buttonMai50.setObjectName("buttonMai50")
        self.gridLayout.addWidget(self.buttonMai50, 8, 0, 1, 1)
        self.buttonBra60 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBra60.sizePolicy().hasHeightForWidth())
        self.buttonBra60.setSizePolicy(sizePolicy)
        self.buttonBra60.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBra60.setCheckable(True)
        self.buttonBra60.setAutoExclusive(True)
        self.buttonBra60.setObjectName("buttonBra60")
        self.gridLayout.addWidget(self.buttonBra60, 4, 0, 1, 1)
        self.buttonAal50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAal50.sizePolicy().hasHeightForWidth())
        self.buttonAal50.setSizePolicy(sizePolicy)
        self.buttonAal50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonAal50.setCheckable(True)
        self.buttonAal50.setAutoExclusive(True)
        self.buttonAal50.setObjectName("buttonAal50")
        self.gridLayout.addWidget(self.buttonAal50, 2, 0, 1, 1)
        self.buttonNas30 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNas30.sizePolicy().hasHeightForWidth())
        self.buttonNas30.setSizePolicy(sizePolicy)
        self.buttonNas30.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonNas30.setCheckable(True)
        self.buttonNas30.setAutoExclusive(True)
        self.buttonNas30.setObjectName("buttonNas30")
        self.gridLayout.addWidget(self.buttonNas30, 1, 2, 1, 1)
        self.buttonMee70 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMee70.sizePolicy().hasHeightForWidth())
        self.buttonMee70.setSizePolicy(sizePolicy)
        self.buttonMee70.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMee70.setCheckable(True)
        self.buttonMee70.setAutoExclusive(True)
        self.buttonMee70.setObjectName("buttonMee70")
        self.gridLayout.addWidget(self.buttonMee70, 6, 0, 1, 1)
        self.buttonBab40 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBab40.sizePolicy().hasHeightForWidth())
        self.buttonBab40.setSizePolicy(sizePolicy)
        self.buttonBab40.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBab40.setCheckable(True)
        self.buttonBab40.setAutoExclusive(True)
        self.buttonBab40.setObjectName("buttonBab40")
        self.gridLayout.addWidget(self.buttonBab40, 3, 2, 1, 1)
        self.buttonBra40 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBra40.sizePolicy().hasHeightForWidth())
        self.buttonBra40.setSizePolicy(sizePolicy)
        self.buttonBra40.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBra40.setCheckable(True)
        self.buttonBra40.setAutoExclusive(True)
        self.buttonBra40.setObjectName("buttonBra40")
        self.gridLayout.addWidget(self.buttonBra40, 4, 2, 1, 1)
        self.buttonNas50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNas50.sizePolicy().hasHeightForWidth())
        self.buttonNas50.setSizePolicy(sizePolicy)
        self.buttonNas50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonNas50.setCheckable(True)
        self.buttonNas50.setAutoExclusive(True)
        self.buttonNas50.setObjectName("buttonNas50")
        self.gridLayout.addWidget(self.buttonNas50, 1, 0, 1, 1)
        self.buttonUke10 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUke10.sizePolicy().hasHeightForWidth())
        self.buttonUke10.setSizePolicy(sizePolicy)
        self.buttonUke10.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonUke10.setCheckable(True)
        self.buttonUke10.setAutoExclusive(True)
        self.buttonUke10.setObjectName("buttonUke10")
        self.gridLayout.addWidget(self.buttonUke10, 0, 0, 1, 1)
        self.buttonMee50 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMee50.sizePolicy().hasHeightForWidth())
        self.buttonMee50.setSizePolicy(sizePolicy)
        self.buttonMee50.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMee50.setCheckable(True)
        self.buttonMee50.setAutoExclusive(True)
        self.buttonMee50.setObjectName("buttonMee50")
        self.gridLayout.addWidget(self.buttonMee50, 6, 2, 1, 1)
        self.buttonMen70 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMen70.sizePolicy().hasHeightForWidth())
        self.buttonMen70.setSizePolicy(sizePolicy)
        self.buttonMen70.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMen70.setCheckable(True)
        self.buttonMen70.setAutoExclusive(True)
        self.buttonMen70.setObjectName("buttonMen70")
        self.gridLayout.addWidget(self.buttonMen70, 9, 2, 1, 1)
        self.buttonMen80 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMen80.sizePolicy().hasHeightForWidth())
        self.buttonMen80.setSizePolicy(sizePolicy)
        self.buttonMen80.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMen80.setCheckable(True)
        self.buttonMen80.setAutoExclusive(True)
        self.buttonMen80.setObjectName("buttonMen80")
        self.gridLayout.addWidget(self.buttonMen80, 9, 1, 1, 1)
        self.buttonNas20 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNas20.sizePolicy().hasHeightForWidth())
        self.buttonNas20.setSizePolicy(sizePolicy)
        self.buttonNas20.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonNas20.setCheckable(True)
        self.buttonNas20.setAutoExclusive(True)
        self.buttonNas20.setObjectName("buttonNas20")
        self.gridLayout.addWidget(self.buttonNas20, 1, 3, 1, 1)
        self.buttonBab60 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBab60.sizePolicy().hasHeightForWidth())
        self.buttonBab60.setSizePolicy(sizePolicy)
        self.buttonBab60.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBab60.setCheckable(True)
        self.buttonBab60.setAutoExclusive(True)
        self.buttonBab60.setObjectName("buttonBab60")
        self.gridLayout.addWidget(self.buttonBab60, 3, 0, 1, 1)
        self.buttonBab30 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBab30.sizePolicy().hasHeightForWidth())
        self.buttonBab30.setSizePolicy(sizePolicy)
        self.buttonBab30.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBab30.setCheckable(True)
        self.buttonBab30.setAutoExclusive(True)
        self.buttonBab30.setObjectName("buttonBab30")
        self.gridLayout.addWidget(self.buttonBab30, 3, 3, 1, 1)
        self.buttonUke0 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUke0.sizePolicy().hasHeightForWidth())
        self.buttonUke0.setSizePolicy(sizePolicy)
        self.buttonUke0.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonUke0.setCheckable(True)
        self.buttonUke0.setAutoExclusive(True)
        self.buttonUke0.setObjectName("buttonUke0")
        self.gridLayout.addWidget(self.buttonUke0, 0, 1, 1, 1)
        self.buttonMee60 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMee60.sizePolicy().hasHeightForWidth())
        self.buttonMee60.setSizePolicy(sizePolicy)
        self.buttonMee60.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonMee60.setCheckable(True)
        self.buttonMee60.setAutoExclusive(True)
        self.buttonMee60.setObjectName("buttonMee60")
        self.gridLayout.addWidget(self.buttonMee60, 6, 1, 1, 1)
        self.buttonBab20 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBab20.sizePolicy().hasHeightForWidth())
        self.buttonBab20.setSizePolicy(sizePolicy)
        self.buttonBab20.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonBab20.setCheckable(True)
        self.buttonBab20.setAutoExclusive(True)
        self.buttonBab20.setObjectName("buttonBab20")
        self.gridLayout.addWidget(self.buttonBab20, 3, 4, 1, 1)
        self.buttonAal20 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAal20.sizePolicy().hasHeightForWidth())
        self.buttonAal20.setSizePolicy(sizePolicy)
        self.buttonAal20.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonAal20.setCheckable(True)
        self.buttonAal20.setAutoExclusive(True)
        self.buttonAal20.setObjectName("buttonAal20")
        self.gridLayout.addWidget(self.buttonAal20, 2, 3, 1, 1)
        self.buttonLac70 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLac70.sizePolicy().hasHeightForWidth())
        self.buttonLac70.setSizePolicy(sizePolicy)
        self.buttonLac70.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonLac70.setCheckable(True)
        self.buttonLac70.setAutoExclusive(True)
        self.buttonLac70.setObjectName("buttonLac70")
        self.gridLayout.addWidget(self.buttonLac70, 10, 1, 1, 1)
        self.buttonUk10 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUk10.sizePolicy().hasHeightForWidth())
        self.buttonUk10.setSizePolicy(sizePolicy)
        self.buttonUk10.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonUk10.setCheckable(True)
        self.buttonUk10.setAutoExclusive(True)
        self.buttonUk10.setObjectName("buttonUk10")
        self.gridLayout.addWidget(self.buttonUk10, 11, 0, 1, 1)
        self.buttonUk0 = QtGui.QPushButton(self.groupBoxArtLaenge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUk0.sizePolicy().hasHeightForWidth())
        self.buttonUk0.setSizePolicy(sizePolicy)
        self.buttonUk0.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonUk0.setCheckable(True)
        self.buttonUk0.setAutoExclusive(True)
        self.buttonUk0.setObjectName("buttonUk0")
        self.gridLayout.addWidget(self.buttonUk0, 11, 1, 1, 1)
        self.buttonUncheckAllFishButtons = QtGui.QPushButton(self.groupBoxArtLaenge)
        self.buttonUncheckAllFishButtons.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUncheckAllFishButtons.sizePolicy().hasHeightForWidth())
        self.buttonUncheckAllFishButtons.setSizePolicy(sizePolicy)
        self.buttonUncheckAllFishButtons.setMinimumSize(QtCore.QSize(51, 22))
        self.buttonUncheckAllFishButtons.setCheckable(True)
        self.buttonUncheckAllFishButtons.setAutoExclusive(True)
        self.buttonUncheckAllFishButtons.setObjectName("buttonUncheckAllFishButtons")
        self.gridLayout.addWidget(self.buttonUncheckAllFishButtons, 11, 5, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxArtLaenge)
        self.groupBoxManuell = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxManuell.sizePolicy().hasHeightForWidth())
        self.groupBoxManuell.setSizePolicy(sizePolicy)
        self.groupBoxManuell.setMinimumSize(QtCore.QSize(281, 64))
        self.groupBoxManuell.setCheckable(True)
        self.groupBoxManuell.setChecked(False)
        self.groupBoxManuell.setObjectName("groupBoxManuell")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBoxManuell)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_art = QtGui.QLabel(self.groupBoxManuell)
        self.label_art.setMinimumSize(QtCore.QSize(1, 30))
        self.label_art.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_art.setObjectName("label_art")
        self.horizontalLayout.addWidget(self.label_art)
        self.comboBoxArt = QtGui.QComboBox(self.groupBoxManuell)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxArt.sizePolicy().hasHeightForWidth())
        self.comboBoxArt.setSizePolicy(sizePolicy)
        self.comboBoxArt.setMinimumSize(QtCore.QSize(170, 27))
        self.comboBoxArt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBoxArt.setObjectName("comboBoxArt")
        self.horizontalLayout.addWidget(self.comboBoxArt)
        self.label_laenge = QtGui.QLabel(self.groupBoxManuell)
        self.label_laenge.setMinimumSize(QtCore.QSize(1, 30))
        self.label_laenge.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_laenge.setObjectName("label_laenge")
        self.horizontalLayout.addWidget(self.label_laenge)
        self.spinBoxLaenge = QtGui.QSpinBox(self.groupBoxManuell)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxLaenge.sizePolicy().hasHeightForWidth())
        self.spinBoxLaenge.setSizePolicy(sizePolicy)
        self.spinBoxLaenge.setMinimumSize(QtCore.QSize(70, 27))
        self.spinBoxLaenge.setMaximumSize(QtCore.QSize(16777215, 30))
        self.spinBoxLaenge.setWrapping(False)
        self.spinBoxLaenge.setReadOnly(False)
        self.spinBoxLaenge.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinBoxLaenge.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBoxLaenge.setKeyboardTracking(True)
        self.spinBoxLaenge.setMaximum(150)
        self.spinBoxLaenge.setSingleStep(10)
        self.spinBoxLaenge.setObjectName("spinBoxLaenge")
        self.horizontalLayout.addWidget(self.spinBoxLaenge)
        self.verticalLayout_3.addWidget(self.groupBoxManuell)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(281, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_bem = QtGui.QTextEdit(self.groupBox_2)
        self.edit_bem.setMaximumSize(QtCore.QSize(9999, 20))
        self.edit_bem.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.edit_bem.setObjectName("edit_bem")
        self.gridLayout_2.addWidget(self.edit_bem, 0, 0, 1, 6)
        self.check_bem = QtGui.QCheckBox(self.groupBox_2)
        self.check_bem.setObjectName("check_bem")
        self.gridLayout_2.addWidget(self.check_bem, 0, 6, 1, 1)
        self.rbtn_blau = QtGui.QRadioButton(self.groupBox_2)
        self.rbtn_blau.setStyleSheet("    QRadioButton{\n"
"    background:rgb(0, 0, 255);\n"
"    }")
        self.rbtn_blau.setText("")
        self.rbtn_blau.setObjectName("rbtn_blau")
        self.gridLayout_2.addWidget(self.rbtn_blau, 1, 0, 1, 1)
        self.rbtn_rot = QtGui.QRadioButton(self.groupBox_2)
        self.rbtn_rot.setStyleSheet("    QRadioButton{\n"
"    background:rgb(255, 0, 0);\n"
"    }")
        self.rbtn_rot.setText("")
        self.rbtn_rot.setObjectName("rbtn_rot")
        self.gridLayout_2.addWidget(self.rbtn_rot, 1, 1, 1, 1)
        self.rbtn_gruen = QtGui.QRadioButton(self.groupBox_2)
        self.rbtn_gruen.setStyleSheet("    QRadioButton{\n"
"    background:rgb(0, 255, 0);\n"
"    }")
        self.rbtn_gruen.setText("")
        self.rbtn_gruen.setObjectName("rbtn_gruen")
        self.gridLayout_2.addWidget(self.rbtn_gruen, 1, 2, 1, 1)
        self.rbtn_gelb = QtGui.QRadioButton(self.groupBox_2)
        self.rbtn_gelb.setStyleSheet("    QRadioButton{\n"
"    background:rgb(255, 255, 0);\n"
"    }")
        self.rbtn_gelb.setText("")
        self.rbtn_gelb.setObjectName("rbtn_gelb")
        self.gridLayout_2.addWidget(self.rbtn_gelb, 1, 3, 1, 1)
        self.rbtn_pink = QtGui.QRadioButton(self.groupBox_2)
        self.rbtn_pink.setStyleSheet("    QRadioButton{\n"
"    background:rgb(255, 0, 255);\n"
"    }")
        self.rbtn_pink.setText("")
        self.rbtn_pink.setObjectName("rbtn_pink")
        self.gridLayout_2.addWidget(self.rbtn_pink, 1, 4, 1, 1)
        self.rbtn_def = QtGui.QRadioButton(self.groupBox_2)
        self.rbtn_def.setStyleSheet("    QRadioButton{\n"
"    background:rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255);\n"
"    }")
        self.rbtn_def.setChecked(True)
        self.rbtn_def.setObjectName("rbtn_def")
        self.gridLayout_2.addWidget(self.rbtn_def, 1, 5, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBoxTruebungTurbulenz = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxTruebungTurbulenz.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBoxTruebungTurbulenz.setObjectName("groupBoxTruebungTurbulenz")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBoxTruebungTurbulenz)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.combo_trueb = QtGui.QComboBox(self.groupBoxTruebungTurbulenz)
        self.combo_trueb.setObjectName("combo_trueb")
        self.horizontalLayout_3.addWidget(self.combo_trueb)
        self.combo_turb = QtGui.QComboBox(self.groupBoxTruebungTurbulenz)
        self.combo_turb.setObjectName("combo_turb")
        self.horizontalLayout_3.addWidget(self.combo_turb)
        self.verticalLayout_3.addWidget(self.groupBoxTruebungTurbulenz)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(241, 65))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonAufstieg = QtGui.QPushButton(self.groupBox_4)
        self.buttonAufstieg.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonAufstieg.setObjectName("buttonAufstieg")
        self.gridLayout_3.addWidget(self.buttonAufstieg, 0, 0, 1, 1)
        self.buttonAbstieg = QtGui.QPushButton(self.groupBox_4)
        self.buttonAbstieg.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonAbstieg.setObjectName("buttonAbstieg")
        self.gridLayout_3.addWidget(self.buttonAbstieg, 0, 1, 1, 1)
        self.buttonKvogno = QtGui.QPushButton(self.groupBox_4)
        self.buttonKvogno.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonKvogno.setObjectName("buttonKvogno")
        self.gridLayout_3.addWidget(self.buttonKvogno, 0, 2, 1, 1)
        self.buttonUnklar = QtGui.QPushButton(self.groupBox_4)
        self.buttonUnklar.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonUnklar.setObjectName("buttonUnklar")
        self.gridLayout_3.addWidget(self.buttonUnklar, 0, 4, 1, 1)
        self.buttonKvugnu = QtGui.QPushButton(self.groupBox_4)
        self.buttonKvugnu.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonKvugnu.setObjectName("buttonKvugnu")
        self.gridLayout_3.addWidget(self.buttonKvugnu, 0, 3, 1, 1)
        self.buttonVonUntenInBox = QtGui.QPushButton(self.groupBox_4)
        self.buttonVonUntenInBox.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonVonUntenInBox.setObjectName("buttonVonUntenInBox")
        self.gridLayout_3.addWidget(self.buttonVonUntenInBox, 1, 0, 1, 1)
        self.buttonVonObenInBox = QtGui.QPushButton(self.groupBox_4)
        self.buttonVonObenInBox.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonVonObenInBox.setObjectName("buttonVonObenInBox")
        self.gridLayout_3.addWidget(self.buttonVonObenInBox, 1, 1, 1, 1)
        self.buttonVonBoxInBox = QtGui.QPushButton(self.groupBox_4)
        self.buttonVonBoxInBox.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonVonBoxInBox.setObjectName("buttonVonBoxInBox")
        self.gridLayout_3.addWidget(self.buttonVonBoxInBox, 1, 2, 1, 1)
        self.buttonVonBoxAuf = QtGui.QPushButton(self.groupBox_4)
        self.buttonVonBoxAuf.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonVonBoxAuf.setObjectName("buttonVonBoxAuf")
        self.gridLayout_3.addWidget(self.buttonVonBoxAuf, 1, 3, 1, 1)
        self.buttonVonBoxAb = QtGui.QPushButton(self.groupBox_4)
        self.buttonVonBoxAb.setMinimumSize(QtCore.QSize(51, 25))
        self.buttonVonBoxAb.setObjectName("buttonVonBoxAb")
        self.gridLayout_3.addWidget(self.buttonVonBoxAb, 1, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(141, 51))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_con = QtGui.QLabel(self.groupBox)
        self.label_con.setText("")
        self.label_con.setObjectName("label_con")
        self.gridLayout_4.addWidget(self.label_con, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Menue = QtGui.QMenu(self.menubar)
        self.menu_Menue.setTitle("&Datenbank")
        self.menu_Menue.setObjectName("menu_Menue")
        self.menu_Neu = QtGui.QMenu(self.menu_Menue)
        self.menu_Neu.setObjectName("menu_Neu")
        self.menu_Editor = QtGui.QMenu(self.menubar)
        self.menu_Editor.setTitle("&Editor")
        self.menu_Editor.setObjectName("menu_Editor")
        self.menu_Ueber = QtGui.QMenu(self.menubar)
        self.menu_Ueber.setObjectName("menu_Ueber")
        self.menuOptionen = QtGui.QMenu(self.menubar)
        self.menuOptionen.setObjectName("menuOptionen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Laden = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/database_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Laden.setIcon(icon)
        self.action_Laden.setObjectName("action_Laden")
        self.actionAnzeigen = QtGui.QAction(MainWindow)
        self.actionAnzeigen.setObjectName("actionAnzeigen")
        self.actionAls_Excel_exportieren = QtGui.QAction(MainWindow)
        self.actionAls_Excel_exportieren.setObjectName("actionAls_Excel_exportieren")
        self.action_Oeffnen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/table_edit_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Oeffnen.setIcon(icon1)
        self.action_Oeffnen.setObjectName("action_Oeffnen")
        self.action_Zuletzt_verwendet = QtGui.QAction(MainWindow)
        self.action_Zuletzt_verwendet.setObjectName("action_Zuletzt_verwendet")
        self.action_Schliessen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/door_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Schliessen.setIcon(icon2)
        self.action_Schliessen.setObjectName("action_Schliessen")
        self.actionServer_DB = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/database_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionServer_DB.setIcon(icon3)
        self.actionServer_DB.setObjectName("actionServer_DB")
        self.actionSub_DB = QtGui.QAction(MainWindow)
        self.actionSub_DB.setIcon(icon3)
        self.actionSub_DB.setObjectName("actionSub_DB")
        self.actionManuelleEingabe = QtGui.QAction(MainWindow)
        self.actionManuelleEingabe.setCheckable(True)
        self.actionManuelleEingabe.setChecked(True)
        self.actionManuelleEingabe.setObjectName("actionManuelleEingabe")
        self.actionTruebungTurbulenz = QtGui.QAction(MainWindow)
        self.actionTruebungTurbulenz.setCheckable(True)
        self.actionTruebungTurbulenz.setChecked(True)
        self.actionTruebungTurbulenz.setObjectName("actionTruebungTurbulenz")
        self.actionBodenplatteButtons = QtGui.QAction(MainWindow)
        self.actionBodenplatteButtons.setCheckable(True)
        self.actionBodenplatteButtons.setChecked(True)
        self.actionBodenplatteButtons.setObjectName("actionBodenplatteButtons")
        self.menu_Neu.addAction(self.actionServer_DB)
        self.menu_Neu.addAction(self.actionSub_DB)
        self.menu_Menue.addAction(self.menu_Neu.menuAction())
        self.menu_Menue.addAction(self.action_Laden)
        self.menu_Menue.addSeparator()
        self.menu_Menue.addAction(self.action_Zuletzt_verwendet)
        self.menu_Menue.addSeparator()
        self.menu_Menue.addAction(self.action_Schliessen)
        self.menu_Editor.addAction(self.action_Oeffnen)
        self.menuOptionen.addAction(self.actionManuelleEingabe)
        self.menuOptionen.addAction(self.actionTruebungTurbulenz)
        self.menuOptionen.addAction(self.actionBodenplatteButtons)
        self.menubar.addAction(self.menu_Menue.menuAction())
        self.menubar.addAction(self.menu_Editor.menuAction())
        self.menubar.addAction(self.menuOptionen.menuAction())
        self.menubar.addAction(self.menu_Ueber.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinbox, self.buttonUke10)
        MainWindow.setTabOrder(self.buttonUke10, self.buttonUke0)
        MainWindow.setTabOrder(self.buttonUke0, self.buttonNas50)
        MainWindow.setTabOrder(self.buttonNas50, self.buttonNas40)
        MainWindow.setTabOrder(self.buttonNas40, self.buttonNas30)
        MainWindow.setTabOrder(self.buttonNas30, self.buttonNas20)
        MainWindow.setTabOrder(self.buttonNas20, self.buttonAal50)
        MainWindow.setTabOrder(self.buttonAal50, self.buttonAal40)
        MainWindow.setTabOrder(self.buttonAal40, self.buttonBab60)
        MainWindow.setTabOrder(self.buttonBab60, self.buttonBab50)
        MainWindow.setTabOrder(self.buttonBab50, self.buttonBab40)
        MainWindow.setTabOrder(self.buttonBab40, self.buttonBab30)
        MainWindow.setTabOrder(self.buttonBab30, self.buttonBra60)
        MainWindow.setTabOrder(self.buttonBra60, self.buttonBra50)
        MainWindow.setTabOrder(self.buttonBra50, self.buttonBra40)
        MainWindow.setTabOrder(self.buttonBra40, self.buttonBra30)
        MainWindow.setTabOrder(self.buttonBra30, self.buttonMee70)
        MainWindow.setTabOrder(self.buttonMee70, self.buttonMee60)
        MainWindow.setTabOrder(self.buttonMee60, self.buttonMee50)
        MainWindow.setTabOrder(self.buttonMee50, self.buttonMai50)
        MainWindow.setTabOrder(self.buttonMai50, self.buttonMen90)
        MainWindow.setTabOrder(self.buttonMen90, self.buttonMen80)
        MainWindow.setTabOrder(self.buttonMen80, self.buttonMen70)
        MainWindow.setTabOrder(self.buttonMen70, self.edit_bem)
        MainWindow.setTabOrder(self.edit_bem, self.rbtn_blau)
        MainWindow.setTabOrder(self.rbtn_blau, self.rbtn_rot)
        MainWindow.setTabOrder(self.rbtn_rot, self.rbtn_gruen)
        MainWindow.setTabOrder(self.rbtn_gruen, self.rbtn_def)
        MainWindow.setTabOrder(self.rbtn_def, self.buttonAufstieg)
        MainWindow.setTabOrder(self.buttonAufstieg, self.buttonAbstieg)
        MainWindow.setTabOrder(self.buttonAbstieg, self.buttonKvogno)
        MainWindow.setTabOrder(self.buttonKvogno, self.buttonUnklar)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Fisdet", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Multiplikator", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Protokollant", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxArtLaenge.setTitle(QtGui.QApplication.translate("MainWindow", "Art und Laenge", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBab10.setText(QtGui.QApplication.translate("MainWindow", "BAB 10", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRot20.setText(QtGui.QApplication.translate("MainWindow", "ROT 20", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRot10.setText(QtGui.QApplication.translate("MainWindow", "ROT 10", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLac60.setText(QtGui.QApplication.translate("MainWindow", "LAC 60", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLac50.setText(QtGui.QApplication.translate("MainWindow", "LAC 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRot30.setText(QtGui.QApplication.translate("MainWindow", "ROT 30", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAal30.setText(QtGui.QApplication.translate("MainWindow", "AAL 30", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMai40.setText(QtGui.QApplication.translate("MainWindow", "MAI 40", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLac80.setText(QtGui.QApplication.translate("MainWindow", "LAC 80", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRot0.setText(QtGui.QApplication.translate("MainWindow", "ROT 0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNas40.setText(QtGui.QApplication.translate("MainWindow", "NAS 40", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAal40.setText(QtGui.QApplication.translate("MainWindow", "AAL 40", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBab50.setText(QtGui.QApplication.translate("MainWindow", "BAB 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBra50.setText(QtGui.QApplication.translate("MainWindow", "BRA 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBra30.setText(QtGui.QApplication.translate("MainWindow", "BRA 30", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMen90.setText(QtGui.QApplication.translate("MainWindow", "MEN 90", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMai50.setText(QtGui.QApplication.translate("MainWindow", "MAI 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBra60.setText(QtGui.QApplication.translate("MainWindow", "BRA 60", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAal50.setText(QtGui.QApplication.translate("MainWindow", "AAL 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNas30.setText(QtGui.QApplication.translate("MainWindow", "NAS 30", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMee70.setText(QtGui.QApplication.translate("MainWindow", "MEE 70", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBab40.setText(QtGui.QApplication.translate("MainWindow", "BAB 40", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBra40.setText(QtGui.QApplication.translate("MainWindow", "BRA 40", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNas50.setText(QtGui.QApplication.translate("MainWindow", "NAS 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUke10.setText(QtGui.QApplication.translate("MainWindow", "UKE 10", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMee50.setText(QtGui.QApplication.translate("MainWindow", "MEE 50", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMen70.setText(QtGui.QApplication.translate("MainWindow", "MEN 70", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMen80.setText(QtGui.QApplication.translate("MainWindow", "MEN 80", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNas20.setText(QtGui.QApplication.translate("MainWindow", "NAS 20", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBab60.setText(QtGui.QApplication.translate("MainWindow", "BAB 60", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBab30.setText(QtGui.QApplication.translate("MainWindow", "BAB 30", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUke0.setText(QtGui.QApplication.translate("MainWindow", "UKE 0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMee60.setText(QtGui.QApplication.translate("MainWindow", "MEE 60", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBab20.setText(QtGui.QApplication.translate("MainWindow", "BAB 20", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAal20.setText(QtGui.QApplication.translate("MainWindow", "AAL 20", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLac70.setText(QtGui.QApplication.translate("MainWindow", "LAC 70", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUk10.setText(QtGui.QApplication.translate("MainWindow", "uK 10", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUk0.setText(QtGui.QApplication.translate("MainWindow", "uK 0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUncheckAllFishButtons.setText(QtGui.QApplication.translate("MainWindow", "uncheck", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxManuell.setTitle(QtGui.QApplication.translate("MainWindow", "manuelle Eingabe:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_art.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"left\">Art:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_laenge.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Länge:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Text und Farbe der Bemerkung", None, QtGui.QApplication.UnicodeUTF8))
        self.check_bem.setToolTip(QtGui.QApplication.translate("MainWindow", "Bemerkung und Farbe für weitere Eingaben fixieren. ", None, QtGui.QApplication.UnicodeUTF8))
        self.check_bem.setStatusTip(QtGui.QApplication.translate("MainWindow", "Bemerkung und Farbe für weitere Eingaben fixieren. ", None, QtGui.QApplication.UnicodeUTF8))
        self.check_bem.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Bemerkung stehen lassen.", None, QtGui.QApplication.UnicodeUTF8))
        self.check_bem.setText(QtGui.QApplication.translate("MainWindow", "fix", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_def.setText(QtGui.QApplication.translate("MainWindow", "default", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTruebungTurbulenz.setTitle(QtGui.QApplication.translate("MainWindow", "Trübung / Turbulenz", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Verhalten", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAufstieg.setText(QtGui.QApplication.translate("MainWindow", "auf", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAbstieg.setText(QtGui.QApplication.translate("MainWindow", "ab", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonKvogno.setText(QtGui.QApplication.translate("MainWindow", "kvogno", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUnklar.setText(QtGui.QApplication.translate("MainWindow", "unklar", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonKvugnu.setText(QtGui.QApplication.translate("MainWindow", "kvugnu", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVonUntenInBox.setText(QtGui.QApplication.translate("MainWindow", "vuiBox", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVonObenInBox.setText(QtGui.QApplication.translate("MainWindow", "voiBox", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVonBoxInBox.setText(QtGui.QApplication.translate("MainWindow", "BiB", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVonBoxAuf.setText(QtGui.QApplication.translate("MainWindow", "Boxauf", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVonBoxAb.setText(QtGui.QApplication.translate("MainWindow", "Boxab", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Zusammenfassung", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Neu.setTitle(QtGui.QApplication.translate("MainWindow", "&Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Ueber.setTitle(QtGui.QApplication.translate("MainWindow", "Ü&ber", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptionen.setTitle(QtGui.QApplication.translate("MainWindow", "Ansicht", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Laden.setText(QtGui.QApplication.translate("MainWindow", "&Laden", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Laden.setStatusTip(QtGui.QApplication.translate("MainWindow", "Datenbank laden.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Laden.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnzeigen.setText(QtGui.QApplication.translate("MainWindow", "&Anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAls_Excel_exportieren.setText(QtGui.QApplication.translate("MainWindow", "als Excel exportieren", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Oeffnen.setText(QtGui.QApplication.translate("MainWindow", "&Öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Oeffnen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Editor öffnen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Oeffnen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Zuletzt_verwendet.setText(QtGui.QApplication.translate("MainWindow", "Zuletzt &verwendet", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Schliessen.setText(QtGui.QApplication.translate("MainWindow", "&Schließen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Schliessen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Programm schließen.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Schliessen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer_DB.setText(QtGui.QApplication.translate("MainWindow", "server-DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer_DB.setToolTip(QtGui.QApplication.translate("MainWindow", "Erstellt eine neue Server-Datenbank. (Administratoren vorbehalten)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer_DB.setStatusTip(QtGui.QApplication.translate("MainWindow", "Erstellt eine neue Server-Datenbank. (Administratoren vorbehalten)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSub_DB.setText(QtGui.QApplication.translate("MainWindow", "sub-DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSub_DB.setToolTip(QtGui.QApplication.translate("MainWindow", "Erstellt eine neue Unterdatenbank.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSub_DB.setStatusTip(QtGui.QApplication.translate("MainWindow", "Erstellt eine neue Unterdatenbank.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSub_DB.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManuelleEingabe.setText(QtGui.QApplication.translate("MainWindow", "Manuelle Eingabe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTruebungTurbulenz.setText(QtGui.QApplication.translate("MainWindow", "Trübung/Turbulenz", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBodenplatteButtons.setText(QtGui.QApplication.translate("MainWindow", "Bodenplatte", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
